/**
 * Google Chronicle (SecOps) MCP Adapter
 * Built on the Epic AI® Intelligence Platform
 * Copyright 2026 protectNIL Inc. Apache-2.0
 */

// Official MCP: https://github.com/google/mcp-security — actively maintained, 4 sub-servers covering Chronicle, SOAR, GTI, and SCC. Also available as a hosted remote server at https://chronicle.us.rep.googleapis.com/mcp. Build this adapter for API-key / service-account bearer-token use cases and air-gapped deployments.

import { ToolDefinition, ToolResult } from './types.js';

// Chronicle is a regional service — requests to the global endpoint return 404.
// Default: US multi-region (https://backstory.googleapis.com).
// Other regions: europe-backstory.googleapis.com, asia-southeast1-backstory.googleapis.com, etc.
// Auth: OAuth 2.0 Bearer token (gcloud auth print-access-token, or service account key).

interface ChronicleConfig {
  accessToken: string;
  baseUrl?: string;
}

export class ChronicleMCPServer {
  private readonly accessToken: string;
  private readonly baseUrl: string;

  constructor(config: ChronicleConfig) {
    this.accessToken = config.accessToken;
    this.baseUrl = config.baseUrl || 'https://backstory.googleapis.com';
  }

  get tools(): ToolDefinition[] {
    return [
      {
        name: 'udm_search',
        description: 'Search UDM (Unified Data Model) events using a YARA-L query. Returns up to 10,000 results with no paging.',
        inputSchema: {
          type: 'object',
          properties: {
            query: {
              type: 'string',
              description: 'UDM search query string (YARA-L syntax)',
            },
            start_time: {
              type: 'string',
              description: 'Start of time range in RFC 3339 format (e.g. 2024-01-01T00:00:00Z)',
            },
            end_time: {
              type: 'string',
              description: 'End of time range in RFC 3339 format',
            },
            limit: {
              type: 'number',
              description: 'Maximum number of events to return (default: 100, max: 10000)',
            },
          },
          required: ['query'],
        },
      },
      {
        name: 'list_alerts',
        description: 'List alerts generated by detection rules in Chronicle',
        inputSchema: {
          type: 'object',
          properties: {
            start_time: {
              type: 'string',
              description: 'Start of time range in RFC 3339 format',
            },
            end_time: {
              type: 'string',
              description: 'End of time range in RFC 3339 format',
            },
            page_size: {
              type: 'number',
              description: 'Maximum number of alerts per page (default: 100)',
            },
            page_token: {
              type: 'string',
              description: 'Pagination token from a previous response',
            },
          },
        },
      },
      {
        name: 'list_rules',
        description: 'List YARA-L detection rules in Chronicle',
        inputSchema: {
          type: 'object',
          properties: {
            page_size: {
              type: 'number',
              description: 'Maximum number of rules per page (default: 100)',
            },
            page_token: {
              type: 'string',
              description: 'Pagination token from a previous response',
            },
          },
        },
      },
      {
        name: 'get_rule',
        description: 'Retrieve a single YARA-L detection rule by rule ID',
        inputSchema: {
          type: 'object',
          properties: {
            rule_id: {
              type: 'string',
              description: 'The rule ID (e.g. ru_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)',
            },
          },
          required: ['rule_id'],
        },
      },
      {
        name: 'search_iocs',
        description: 'Search for indicators of compromise (IoCs) in Chronicle ingested data',
        inputSchema: {
          type: 'object',
          properties: {
            ioc_value: {
              type: 'string',
              description: 'IoC value to search: domain name, IP address, or file hash',
            },
            start_time: {
              type: 'string',
              description: 'Start of time range in RFC 3339 format',
            },
            end_time: {
              type: 'string',
              description: 'End of time range in RFC 3339 format',
            },
            page_size: {
              type: 'number',
              description: 'Maximum number of results (default: 100)',
            },
          },
          required: ['ioc_value'],
        },
      },
      {
        name: 'list_ioc_details',
        description: 'Get threat intelligence details for a specific IoC artifact from Chronicle',
        inputSchema: {
          type: 'object',
          properties: {
            artifact_indicator: {
              type: 'string',
              description: 'IoC artifact: IP address, domain name, or file MD5/SHA256 hash',
            },
          },
          required: ['artifact_indicator'],
        },
      },
      {
        name: 'get_event',
        description: 'Retrieve a single UDM event by its event ID',
        inputSchema: {
          type: 'object',
          properties: {
            event_id: {
              type: 'string',
              description: 'The unique UDM event ID to retrieve',
            },
          },
          required: ['event_id'],
        },
      },
      {
        name: 'list_assets',
        description: 'List Chronicle assets associated with a hostname or IP address and their alert history',
        inputSchema: {
          type: 'object',
          properties: {
            hostname: {
              type: 'string',
              description: 'Hostname to look up (mutually exclusive with ip_address)',
            },
            ip_address: {
              type: 'string',
              description: 'IP address to look up (mutually exclusive with hostname)',
            },
            start_time: {
              type: 'string',
              description: 'Start of time range in RFC 3339 format',
            },
            end_time: {
              type: 'string',
              description: 'End of time range in RFC 3339 format',
            },
            page_size: {
              type: 'number',
              description: 'Maximum number of assets to return (default: 100)',
            },
          },
        },
      },
    ];
  }

  async callTool(name: string, args: Record<string, unknown>): Promise<ToolResult> {
    try {
      const headers: Record<string, string> = {
        Authorization: `Bearer ${this.accessToken}`,
        'Content-Type': 'application/json',
      };

      switch (name) {
        case 'udm_search': {
          const query = args.query as string;
          if (!query) {
            return { content: [{ type: 'text', text: 'query is required' }], isError: true };
          }

          const body: Record<string, unknown> = { query };
          if (args.start_time) body.startTime = args.start_time;
          if (args.end_time) body.endTime = args.end_time;
          if (args.limit) body.limit = args.limit;

          const response = await fetch(`${this.baseUrl}/v2/events:udmSearch`, {
            method: 'POST',
            headers,
            body: JSON.stringify(body),
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `UDM search failed (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'list_alerts': {
          const params = new URLSearchParams();
          if (args.start_time) params.set('startTime', args.start_time as string);
          if (args.end_time) params.set('endTime', args.end_time as string);
          if (args.page_size) params.set('pageSize', String(args.page_size));
          if (args.page_token) params.set('pageToken', args.page_token as string);

          const response = await fetch(`${this.baseUrl}/v2/alert/alertinfos?${params.toString()}`, {
            method: 'GET',
            headers,
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `Failed to list alerts (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'list_rules': {
          const params = new URLSearchParams();
          if (args.page_size) params.set('pageSize', String(args.page_size));
          if (args.page_token) params.set('pageToken', args.page_token as string);

          const response = await fetch(`${this.baseUrl}/v2/detect/rules?${params.toString()}`, {
            method: 'GET',
            headers,
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `Failed to list rules (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'get_rule': {
          const ruleId = args.rule_id as string;
          if (!ruleId) {
            return { content: [{ type: 'text', text: 'rule_id is required' }], isError: true };
          }

          const response = await fetch(`${this.baseUrl}/v2/detect/rules/${encodeURIComponent(ruleId)}`, {
            method: 'GET',
            headers,
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `Failed to get rule (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'search_iocs': {
          const iocValue = args.ioc_value as string;
          if (!iocValue) {
            return { content: [{ type: 'text', text: 'ioc_value is required' }], isError: true };
          }

          const params = new URLSearchParams();
          params.set('artifactIndicator.domainName', iocValue);
          if (args.start_time) params.set('startTime', args.start_time as string);
          if (args.end_time) params.set('endTime', args.end_time as string);
          if (args.page_size) params.set('pageSize', String(args.page_size));

          const response = await fetch(`${this.baseUrl}/v2/ioc:searchAssociations?${params.toString()}`, {
            method: 'GET',
            headers,
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `IoC search failed (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'list_ioc_details': {
          const artifact = args.artifact_indicator as string;
          if (!artifact) {
            return { content: [{ type: 'text', text: 'artifact_indicator is required' }], isError: true };
          }

          const response = await fetch(
            `${this.baseUrl}/v2/ioc/details?artifact.domainName=${encodeURIComponent(artifact)}`,
            { method: 'GET', headers }
          );

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `Failed to get IoC details (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'get_event': {
          const eventId = args.event_id as string;
          if (!eventId) {
            return { content: [{ type: 'text', text: 'event_id is required' }], isError: true };
          }

          const response = await fetch(`${this.baseUrl}/v2/events/${encodeURIComponent(eventId)}`, {
            method: 'GET',
            headers,
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `Failed to get event (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        case 'list_assets': {
          const params = new URLSearchParams();
          if (args.hostname) params.set('hostname', args.hostname as string);
          if (args.ip_address) params.set('destinationIpAddress', args.ip_address as string);
          if (args.start_time) params.set('startTime', args.start_time as string);
          if (args.end_time) params.set('endTime', args.end_time as string);
          if (args.page_size) params.set('pageSize', String(args.page_size));

          const response = await fetch(`${this.baseUrl}/v2/asset/listAlerts?${params.toString()}`, {
            method: 'GET',
            headers,
          });

          if (!response.ok) {
            const errText = await response.text();
            return { content: [{ type: 'text', text: `Failed to list assets (HTTP ${response.status}): ${errText}` }], isError: true };
          }

          let data: unknown;
          try { data = await response.json(); } catch { throw new Error(`Chronicle returned non-JSON response (HTTP ${response.status})`); }
          return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }], isError: false };
        }

        default:
          return { content: [{ type: 'text', text: `Unknown tool: ${name}` }], isError: true };
      }
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Tool execution failed: ${error instanceof Error ? error.message : String(error)}` }],
        isError: true,
      };
    }
  }
}
