/**
 * StatSocial MCP Adapter
 * Built on the Epic AI® Intelligence Platform
 * Copyright 2026 protectNIL Inc. Apache-2.0
 */

// Official MCP: None found as of 2026-03-28
// No official StatSocial MCP server was found on GitHub as of 2026-03-28.
// Our adapter covers: 7 tools. Vendor MCP covers: 0 tools (none exists).
// Recommendation: use-our-adapter — no official MCP server exists.
//
// Base URL: http://api.statsocial.com/api
// Auth: API key passed as query parameter 'key' on every request.
// Docs: http://docs.statsocial.com/home/
// Rate limits: Rate limiting enforced (HTTP 403 when exceeded); avoid polling

import { ToolDefinition, ToolResult } from './types.js';
import { MCPAdapterBase } from './base.js';

interface StatSocialConfig {
  apiKey: string;
  baseUrl?: string;
}

export class StatSocialMCPServer extends MCPAdapterBase {
  private readonly apiKey: string;
  private readonly baseUrl: string;

  constructor(config: StatSocialConfig) {
    super();
    this.apiKey = config.apiKey;
    this.baseUrl = config.baseUrl || 'http://api.statsocial.com/api';
  }

  get tools(): ToolDefinition[] {
    return [
      {
        name: 'get_application_status',
        description: 'Retrieve API usage status including rate limit window, remaining request count, and list of reports generated by this account.',
        inputSchema: {
          type: 'object',
          properties: {},
        },
      },
      {
        name: 'get_report',
        description: 'Fetch a generated audience analytics report by report hash. Returns demographic, geographic, and affinity data with statistical metrics.',
        inputSchema: {
          type: 'object',
          properties: {
            report_hash: {
              type: 'string',
              description: 'Unique hash identifier for the report to retrieve.',
            },
            baseline: {
              type: 'number',
              description: 'Baseline comparison group ID. Defaults to world baseline if omitted.',
            },
            report_date: {
              type: 'number',
              description: 'Unix timestamp of the report version to retrieve. Defaults to the latest generated report. Use get_report_dates to list available timestamps.',
            },
            sample: {
              type: 'number',
              description: 'Sample report indicator (default: 1).',
            },
          },
          required: ['report_hash'],
        },
      },
      {
        name: 'get_report_dates',
        description: 'List available report generation dates (as Unix timestamps) for a given report hash. Use these timestamps with get_report to fetch historical versions.',
        inputSchema: {
          type: 'object',
          properties: {
            report_hash: {
              type: 'string',
              description: 'Unique hash identifier for the report.',
            },
          },
          required: ['report_hash'],
        },
      },
      {
        name: 'get_report_status',
        description: 'Check the processing status of a report by its hash. Returns whether the report is pending, processing, or complete.',
        inputSchema: {
          type: 'object',
          properties: {
            report_hash: {
              type: 'string',
              description: 'Unique hash identifier for the report to check.',
            },
          },
          required: ['report_hash'],
        },
      },
      {
        name: 'create_custom_report',
        description: 'Create a new custom audience analytics report by specifying audience criteria. Returns a report hash for tracking and retrieval.',
        inputSchema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              description: 'Display name for the custom report.',
            },
            description: {
              type: 'string',
              description: 'Optional description of the custom report audience.',
            },
          },
          required: ['name'],
        },
      },
      {
        name: 'create_tweet_report',
        description: 'Generate an audience analytics report from a list of Twitter/X usernames. Analyzes followers and audience demographics.',
        inputSchema: {
          type: 'object',
          properties: {
            handles: {
              type: 'string',
              description: 'Comma-separated list of Twitter/X usernames (without @ symbol) to analyze.',
            },
            name: {
              type: 'string',
              description: 'Optional display name for the report.',
            },
          },
          required: ['handles'],
        },
      },
      {
        name: 'create_twitter_report',
        description: 'Generate an audience analytics report from Twitter/X account data including followers, following, and engagement patterns.',
        inputSchema: {
          type: 'object',
          properties: {
            handles: {
              type: 'string',
              description: 'Comma-separated list of Twitter/X usernames (without @ symbol) to analyze.',
            },
            name: {
              type: 'string',
              description: 'Optional display name for the report.',
            },
          },
          required: ['handles'],
        },
      },
    ];
  }

  async callTool(name: string, args: Record<string, unknown>): Promise<ToolResult> {
    try {
      switch (name) {
        case 'get_application_status':
          return await this.getApplicationStatus();
        case 'get_report':
          return await this.getReport(args);
        case 'get_report_dates':
          return await this.getReportDates(args);
        case 'get_report_status':
          return await this.getReportStatus(args);
        case 'create_custom_report':
          return await this.createCustomReport(args);
        case 'create_tweet_report':
          return await this.createTweetReport(args);
        case 'create_twitter_report':
          return await this.createTwitterReport(args);
        default:
          return { content: [{ type: 'text', text: `Unknown tool: ${name}` }], isError: true };
      }
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Tool execution failed: ${error instanceof Error ? error.message : String(error)}` }],
        isError: true,
      };
    }
  }

  private async request(path: string, method: string = 'GET', body?: Record<string, unknown>): Promise<ToolResult> {
    const separator = path.includes('?') ? '&' : '?';
    const url = `${this.baseUrl}${path}${separator}key=${encodeURIComponent(this.apiKey)}`;

    const response = await this.fetchWithRetry(url, {
      method,
      headers: {
        'Content-Type': 'application/json',
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => response.statusText);
      return {
        content: [{ type: 'text', text: `StatSocial API error ${response.status}: ${errText}` }],
        isError: true,
      };
    }

    let data: unknown;
    try {
      data = await response.json();
    } catch {
      throw new Error(`StatSocial returned non-JSON response (HTTP ${response.status})`);
    }

    const text = JSON.stringify(data, null, 2);
    const truncated = text.length > 10_000
      ? text.slice(0, 10_000) + '\n... [truncated, ' + text.length + ' total chars]'
      : text;

    return { content: [{ type: 'text', text: truncated }], isError: false };
  }

  private async getApplicationStatus(): Promise<ToolResult> {
    return this.request('/applications/status/');
  }

  private async getReport(args: Record<string, unknown>): Promise<ToolResult> {
    const reportHash = args.report_hash as string;
    if (!reportHash) {
      return { content: [{ type: 'text', text: 'report_hash is required' }], isError: true };
    }
    const params = new URLSearchParams({ report_hash: reportHash });
    if (args.baseline !== undefined) params.set('baseline', String(args.baseline));
    if (args.report_date !== undefined) params.set('report_date', String(args.report_date));
    const sample = (args.sample as number) ?? 1;
    params.set('sample', String(sample));
    return this.request(`/reports/?${params.toString()}`);
  }

  private async getReportDates(args: Record<string, unknown>): Promise<ToolResult> {
    const reportHash = args.report_hash as string;
    if (!reportHash) {
      return { content: [{ type: 'text', text: 'report_hash is required' }], isError: true };
    }
    return this.request(`/reports/dates/?report_hash=${encodeURIComponent(reportHash)}`);
  }

  private async getReportStatus(args: Record<string, unknown>): Promise<ToolResult> {
    const reportHash = args.report_hash as string;
    if (!reportHash) {
      return { content: [{ type: 'text', text: 'report_hash is required' }], isError: true };
    }
    return this.request(`/reports/status/?report_hash=${encodeURIComponent(reportHash)}`);
  }

  private async createCustomReport(args: Record<string, unknown>): Promise<ToolResult> {
    const name = args.name as string;
    if (!name) {
      return { content: [{ type: 'text', text: 'name is required' }], isError: true };
    }
    const body: Record<string, unknown> = { name };
    if (args.description) body.description = args.description;
    return this.request('/reports/custom/create/', 'POST', body);
  }

  private async createTweetReport(args: Record<string, unknown>): Promise<ToolResult> {
    const handles = args.handles as string;
    if (!handles) {
      return { content: [{ type: 'text', text: 'handles is required' }], isError: true };
    }
    const body: Record<string, unknown> = { handles };
    if (args.name) body.name = args.name;
    return this.request('/reports/tweet/create/', 'POST', body);
  }

  private async createTwitterReport(args: Record<string, unknown>): Promise<ToolResult> {
    const handles = args.handles as string;
    if (!handles) {
      return { content: [{ type: 'text', text: 'handles is required' }], isError: true };
    }
    const body: Record<string, unknown> = { handles };
    if (args.name) body.name = args.name;
    return this.request('/reports/twitter/create/', 'POST', body);
  }

  static catalog() {
    return {
      name: 'statsocial',
      displayName: 'StatSocial',
      version: '1.0.0',
      category: 'analytics' as const,
      keywords: ['statsocial', 'analytics', 'audience', 'social', 'twitter', 'demographics', 'affinity', 'report', 'influencer'],
      toolNames: ['get_application_status', 'get_report', 'get_report_dates', 'get_report_status', 'create_custom_report', 'create_tweet_report', 'create_twitter_report'],
      description: 'StatSocial audience analytics platform: generate and retrieve demographic, affinity, and social audience reports from Twitter/X data.',
      author: 'protectnil' as const,
    };
  }
}
